In [1]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon
from sklearn.metrics import mean_squared_error
np.set_printoptions(suppress=True)

In [4]:
data = pd.read_csv('./data/district_covariates/all_covariates_clustered.csv')
data.head()

,district,reg_year,reg_month,count_lag_month,count_lag_year,count,male_15_24yr_2011,total_population_2011,sex_ratio_2011,total_non_worker,gdp_2011_12,class
0,Agra,2016,1,1235,1235,1235,588704.0,4558268.0,844.0,3028953.0,13058.94,2
1,Agra,2016,2,1235,1192,1192,588704.0,4558268.0,844.0,3028953.0,13058.94,2
2,Agra,2016,3,1192,1160,1160,588704.0,4558268.0,844.0,3028953.0,13058.94,2
3,Agra,2016,4,1160,1160,1160,588704.0,4558268.0,844.0,3028953.0,13058.94,2
4,Agra,2016,5,1160,1409,1409,588704.0,4558268.0,844.0,3028953.0,13058.94,2

#### Normalizing

In [6]:
# removing columns that dont need normalisation
cols = data.columns
normalise_cols = list(set(cols)-set(['count', 'district', 'class', 'count_lag_year'
                                     , 'count_lag_month', 'reg_month', 'reg_year', 'sex_ratio_2011']))
# normalising columns
df = data.copy()
for colname in normalise_cols:
    df[colname] = (data[colname] - data[colname].min())/(data[colname].max() - data[colname].min())
data = df.copy()
data.head()

,district,reg_year,reg_month,count_lag_month,count_lag_year,count,male_15_24yr_2011,total_population_2011,sex_ratio_2011,total_non_worker,gdp_2011_12,class
0,Agra,2016,1,1235,1235,1235,0.790661,0.734132,844.0,0.75468,0.707565,2
1,Agra,2016,2,1235,1192,1192,0.790661,0.734132,844.0,0.75468,0.707565,2
2,Agra,2016,3,1192,1160,1160,0.790661,0.734132,844.0,0.75468,0.707565,2
3,Agra,2016,4,1160,1160,1160,0.790661,0.734132,844.0,0.75468,0.707565,2
4,Agra,2016,5,1160,1409,1409,0.790661,0.734132,844.0,0.75468,0.707565,2

In [7]:
districts = data['district'].unique()                      # 'districts' contains list of unique districts names
num_districts = len(districts)                             # 'num_districts' contains no. of unique districts
dist_lookup = dict(zip(districts, range(num_districts)))   # 'dist_lookup' is a dict, ex. ['agra':0, ... ]
districts_code_all = data['district_code'] = data.district.replace(dist_lookup).values
print('#of districts: ', num_districts)

#of districts:  75

# StanModel

In [8]:
import pystan

In [9]:
try:
    model = pickle.load(open('./model/no_pooling.pkl', 'rb'))
except:
    model_code = """
    data {
        int<lower=1>         N;                      // number of districts
        int<lower=1>         M;                      // number of months
        int<lower=1>         num_attr;               // number of attributes
        int<lower=N>         sigma_error_dof;        // (degree_of_freedom)parameter for inv_wishart prior on sigma_error
        real<lower=0.0>      alpha_mean;                         
        real<lower=0.0>      alpha_variance;
        real<lower=0.0>      beta_mean;
        real<lower=0.0>      beta_variance;
        real<lower=0.0>      sigma_error_variance;   // diagonal value for matrix, parameter for inv_wishart
        
        matrix[M, num_attr]  X[N];
        vector[N]            crime_count[M];
    }

    parameters {
        vector[N]            alpha;
        vector[num_attr]     beta[N];
        cov_matrix[N]        sigma_err;
    }

    transformed parameters {
        vector[N]            crime_count_hat[M];
        for(j in 1:N) {
            for(t in 1:M) {
                crime_count_hat[t, j] = alpha[j] + dot_product(X[j, t], beta[j]);
            }
        }
    }
    
    model {
        for(j in 1:N){
            alpha[j]       ~    normal(alpha_mean, alpha_variance);
            beta[j]        ~    multi_normal(rep_vector(beta_mean, num_attr), diag_matrix(rep_vector(beta_variance,num_attr)));
        }
        sigma_err   ~    inv_wishart(sigma_error_dof, diag_matrix(rep_vector(sigma_error_variance,N)));
        for(t in 1:M){
            crime_count[t] ~  multi_normal(crime_count_hat[t], sigma_err);
        }
    }
    """
    model = pystan.model.StanModel(model_code=model_code, model_name='no_pooling')
    with open('./model/no_pooling.pkl', 'wb') as f:
        pickle.dump(model, f)

INFO:pystan:COMPILING THE C++ CODE FOR MODEL no_pooling_706add3bf7f3c96f9595dc8c7e1c81ca NOW.

In [10]:
def getCluster(num):
    if num is not -1:
        return  data[data['class']==num]
    else:
        return data.copy()

def getTrainTestDataFor(cluster, train_month, test_month):
    dist_nms = cluster['district'].unique()
    cols = ['male_15_24yr_2011', 'total_population_2011', 'total_non_worker', 'gdp_2011_12', 'count_lag_month', 'count_lag_year']
    #cols = ['sex_ratio_2011', 'male_15_24yr_2011', 'total_non_worker', 'gdp_2011_12', 'count_lag_month', 'count_lag_year']
    x_data = []
    y_data = []
    for dn in dist_nms:
        x_data.append(data[data['district'] == dn][cols].values)
        y_data.append(data[data['district'] == dn]['count'].values)
    x_data = np.array(x_data)
    y_data = np.array(y_data)
    return x_data[::,:train_month,::], y_data[:,:train_month], x_data[::,-test_month:,::], y_data[:,-test_month:]

def plotgraph(actual, predicted, months, years, clust_num, title, save, df):
    numPlots = predicted.size/12
    plt.figure(figsize=(12, 4))
    plt.suptitle(title)
    for i in range(int(numPlots)):
        index = i*12
        plt.subplot(130+i+1)
        plt.plot(months[index:index+12], actual[index:index+12], label='Actual')
        plt.plot(months[index:index+12], predicted[index:index+12], label='Predicted')
        mse = mean_squared_error(actual[index:index+12], predicted[index:index+12])
        df.loc[df['district'] == title, [str(np.unique(years[index:index+12])[0])]] = int(mse)
        plt.legend()
        plt.title(str(np.unique(years[index:index+12])) + ' mse: ' + str(int(mse)))
    plt.subplots_adjust(top=0.80)
    if save:
        plt.savefig('./images/np/{}.png'.format(title), bbox_inches='tight')
    #plt.close()

In [11]:
cluster_num     = -1
training_months = 24
testing_months  = 36

clust    = getCluster(cluster_num)
dist_nms = clust['district'].unique()
X_train, Y_train, X_test, Y_test = getTrainTestDataFor(clust, training_months, testing_months)
print('Shape of X_train, Y_train, X_test, Y_test')
print(X_train.shape, Y_train.shape, X_test.shape, Y_test.shape)
print('Number of districts: ', dist_nms.size)

Shape of X_train, Y_train, X_test, Y_test
(75, 24, 6) (75, 24) (75, 36, 6) (75, 36)
Number of districts:  75

In [12]:
num_attr              = X_train.shape[2]
sigma_error_dof       = dist_nms.size           # should be >= 0
alpha_mean            = 0.0                     # should be >= 0
alpha_variance        = 100.0                   # should be >= 0
beta_mean             = 0.0                     # should be >= 0
beta_variance         = 100.0                    # should be >= 0
sigma_error_variance  = 100                    # should be >= 0

In [13]:
data_dict = {
    'N'                    : dist_nms.size,                  #Number of districts
    'M'                    : training_months,                #Number of training months
    'num_attr'             : num_attr,
    'sigma_error_dof'      : sigma_error_dof,
    'alpha_mean'           : alpha_mean,
    'alpha_variance'       : alpha_variance,
    'beta_mean'            : beta_mean,
    'beta_variance'        : beta_variance,
    'sigma_error_variance' : sigma_error_variance,
    'X'                    : X_train,
    'crime_count'          : Y_train.T
}

In [14]:
model_fit = model.sampling(data=data_dict, iter=1000, chains=6, warmup=400, n_jobs=-1, seed=np.random.randint(100), 
                  control=dict(max_treedepth=12, adapt_delta=0.80), check_hmc_diagnostics=True)

RuntimeError: Exception: inv_wishart_lpdf: LDLT_Factor of random variable is not positive definite.  last conditional variance is -4.44089e-16.  (in 'unknown file name' at line 37)

In [ ]:
beta = np.mean(model_fit.extract()['beta'], axis = 0)
alpha = np.mean(model_fit.extract()['alpha'], axis = 0)
print(alpha.shape, beta.shape)
print(alpha, '\n', beta)